---
abstract: 'SMS::Send driver to send via smsdiscount.com'
author:
  - 'Mark Hindess <soft-cpan@temporalanomaly.com>'
build_requires:
  LWP::Protocol::PSGI: '0'
  LWP::Protocol::https: '0'
  Plack::Request: '0'
  SMS::Send: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.141520'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: SMS-Send-SMSDiscount
requires:
  HTTP::Request::Common: '0'
  LWP::UserAgent: '0'
  SMS::Send::Driver: '0'
  URI::Escape: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/beanz/sms-send-smsdiscount-perl/issues
  homepage: http://search.cpan.org/dist/SMS-Send-SMSDiscount/
  repository: git://github.com/beanz/sms-send-smsdiscount-perl.git
version: '1.142000'
